### ISSUE TITLE
SpringSecurity+JWT를 이용한 인증,인가 및 권한부여 구현

### ISSUE THREAD

**Issue by Jimoou** [udemy-final-team2/Book-Hub-Project#65]
JWT(Json With Token)방식으로 데이터 액세스 인가,인증 및 권한 부여 메커니즘을 구현하고 제어한다.

* [x] 신뢰할 수 있는 Spring Security + JWT 예제 강의를 찾고, 학습하여 JWT 발급 과정 메커니즘을 이해한다.
* [x] 이해한 내용을 바탕으로 직접 그림을 그린다.

* [x] JWT발급으로 인해 수정되는 로직을 팀원들에게 공지하고, 작업을 시작한다.
    - UserService
    - UserController
    - UserRepository
    - UserDTO
    - user-mapper
* [x] 강의를 토대로 JWT 발급 코드를 작성하고, 디렉토리를 수정한다.

* [x] JWT 코드를 따라 작성했다면, 디버깅을 통해, 각종 메서드에 어떤값이 들어오는지 확인한다.
* [x] 이해한 내용을 바탕으로 when/then/given 방식으로 테스트 코드를 작성한다.
* [x] JWT 토큰에 id, email, nickname을 담는다.
* [x] 테스트 코드를 작성해서 정상 작동이 확인 되었다면, JSP와 연계할 수 있는 방법을 찾아본다.
* [x] #75
* [x] 사전 조사에 의하면, JSP와 연계가 안된다는 내용이 있었지만, JSP 연계가 가능하게끔 우선적으로 시도한다.
