### ISSUE TITLE
AWS EC2, RDS, S3를 이용한 프로젝트 배포

### ISSUE THREAD

**Issue by Hambak-note** [udemy-final-team2/Book-Hub-Project#70]
AWS EC2, RDS, S3를 이용하여 진행 프로젝트를 배포한다.

* [ ] 1. RDS를 Local 환경과 연동 테스트 한다.
   * [ ] - RDS를 mariaDB 기반으로 생성한다.
   * [ ] - 데이터베이스와 테이블을 생성하고 local과 연동이 되는지 테스트 해본다.

* [ ] 2. S3를 Local 환경과 연동 테스트 한다.
